name: "CI/CD"
on: 
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build .
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH
      run: mkdir ~/.ssh
    - name: Write SSH Key
      run: echo $FILE_DATA > temp && cat temp | base64 -d > ~/.ssh/id_rsa && rm temp && md5sum ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      env:
        FILE_DATA: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      run: git push dokku@minipaas.xeserv.us:since HEAD:master
      env:
        GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
